import type { TaskWorkspaceData } from "./task-types";

const accounts = [
  { id: "11111111-1111-4111-8111-111111111111", label: "Moree", avatarUrl: null },
  { id: "22222222-2222-4222-8222-222222222222", label: "Wdym", avatarUrl: null },
];

export const taskPreviewData: TaskWorkspaceData = {
  accounts,
  projects: [
    { id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", name: "Soundness", logoUrl: null, accounts, wallets: [] },
    { id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb", name: "NexusHQ", logoUrl: null, accounts: [accounts[0]], wallets: [] },
  ],
  tasks: [
    {
      id: "task-preview-proof",
      projectId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      projectName: "Soundness",
      projectLogoUrl: null,
      title: "Submit proof after address generated",
      description: "Upload the proof link before the reset window closes.",
      status: "todo",
      frequency: "once",
      priority: "high",
      url: "https://example.com",
      sortOrder: 0,
      startDate: "2026-07-21",
      completedAt: null,
      assignedAccounts: [accounts[0]],
      effectiveAccounts: [accounts[0]],
      usesProjectAccountFallback: false,
      assignedWallet: null,
      createdAt: null,
      updatedAt: null,
    },
    {
      id: "task-preview-daily",
      projectId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      projectName: "Soundness",
      projectLogoUrl: null,
      title: "Daily dashboard check-in",
      description: null,
      status: "in_progress",
      frequency: "daily",
      priority: "medium",
      url: null,
      sortOrder: 1,
      startDate: "2026-07-22",
      completedAt: null,
      assignedAccounts: [],
      effectiveAccounts: accounts,
      usesProjectAccountFallback: true,
      assignedWallet: null,
      createdAt: null,
      updatedAt: null,
    },
    {
      id: "task-preview-node",
      projectId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      projectName: "NexusHQ",
      projectLogoUrl: null,
      title: "Run prover node",
      description: "Keep the prover process alive and check logs twice daily.",
      status: "running",
      frequency: "custom",
      priority: "high",
      url: null,
      sortOrder: 2,
      startDate: "2026-07-10",
      completedAt: null,
      assignedAccounts: [accounts[0]],
      effectiveAccounts: [accounts[0]],
      usesProjectAccountFallback: false,
      assignedWallet: null,
      createdAt: null,
      updatedAt: null,
    },
    {
      id: "task-preview-recheck",
      projectId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      projectName: "Soundness",
      projectLogoUrl: null,
      title: "Recheck eligibility result",
      description: "Review the latest eligibility response.",
      status: "recheck",
      frequency: "once",
      priority: "medium",
      url: null,
      sortOrder: 3,
      startDate: "2026-07-25",
      completedAt: null,
      assignedAccounts: [accounts[1]],
      effectiveAccounts: [accounts[1]],
      usesProjectAccountFallback: false,
      assignedWallet: null,
      createdAt: null,
      updatedAt: null,
    },
  ],
};
