import type {
  ProjectsWorkspaceData,
} from "@/features/projects/actions";

const accountOptions: ProjectsWorkspaceData["accountOptions"] = [
  { id: "preview-account-moree", label: "Moree", avatarUrl: null },
  { id: "preview-account-wdym", label: "Wdym", avatarUrl: null },
];

const walletOptions: ProjectsWorkspaceData["walletOptions"] = [
  {
    id: "preview-wallet-1",
    label: "Moree main",
    address: "0x8f3cf7ad23cd3cadbd9735aff958023239c6a063",
    ownerAccountId: "preview-account-moree",
    chainType: "EVM",
    walletType: "main",
  },
];

export const projectsPreviewData: ProjectsWorkspaceData = {
  nftCount: 0,
  accountOptions,
  walletOptions,
  projects: [
    {
      id: "preview-project-soundness",
      workspaceId: "preview-workspace",
      name: "Soundness",
      slug: null,
      description: null,
      logoUrl: null,
      logoPath: null,
      logoSource: "none",
      huntType: "free_hunts",
      status: "in_progress",
      priority: "high",
      workTypes: ["Testnet registration", "Testnet", "Submit proof"],
      projectTypes: ["ZK", "Verif layer"],
      chains: [],
      progressEstimate: "50",
      stageResult: "Submitted proof",
      dateStart: null,
      dateEnd: null,
      websiteUrl: null,
      twitterUrl: null,
      discordUrl: null,
      githubUrl: null,
      docsUrl: null,
      notes: "Proof submitted on the testnet coordinator.",
      isArchived: false,
      archiveReason: null,
      archivedAt: null,
      createdAt: new Date("2026-03-23T02:00:00.000Z"),
      updatedAt: new Date("2026-07-30T09:00:00.000Z"),
      assignedAccounts: [accountOptions[0], accountOptions[1]],
      assignedWallets: [walletOptions[0]],
    },
    {
      id: "preview-project-nexus",
      workspaceId: "preview-workspace",
      name: "NexusHQ",
      slug: null,
      description: null,
      logoUrl: null,
      logoPath: null,
      logoSource: "none",
      huntType: "free_hunts",
      status: "running",
      priority: "medium",
      workTypes: ["CLI running", "Point system"],
      projectTypes: ["Prover", "Node"],
      chains: [],
      progressEstimate: "72",
      stageResult: "Node running",
      dateStart: null,
      dateEnd: null,
      websiteUrl: "https://nexus.xyz",
      twitterUrl: null,
      discordUrl: null,
      githubUrl: null,
      docsUrl: null,
      notes: null,
      isArchived: false,
      archiveReason: null,
      archivedAt: null,
      createdAt: new Date("2025-10-10T02:00:00.000Z"),
      updatedAt: new Date("2026-07-31T11:30:00.000Z"),
      assignedAccounts: [accountOptions[0]],
      assignedWallets: [],
    },
  ],
};
